const PLANET_PARAMS = { # Currently just generated by AI
	# Planet index
	0: {
		"name": "Terra",
		"classification": "Terran Wet",
		"population": "10 billion",
		"dom_species": "Human",
		"tech_level": "Space Age",
		"resources": "Diverse and abundant, but increasingly strained",
		"desc": "Terra is a striking blue and green orb teeming with life and energy. It houses a complex species known as humans, who have developed diverse cultures and advanced technologies. Despite their achievements in space exploration and scientific innovation, they face considerable challenges, including environmental degradation and social conflicts, reflecting both the planet’s beauty and its ongoing struggles.",
		"game_vars": {
			"scale_factor": 1,
			"anim_name": "Planet0",
			"spritesheet": "res://Assets/Sprites/Planets/twplanet1.png",
			"scan_cost": 10000
		}
	},
	# Planet index
	1: {
		"name": "Aqua Serpentine",
		"classification": "Terran Wet",
		"population": "5 billion",
		"dom_species": "Aquatic Serpentians",
		"tech_level": "Industrial Age",
		"resources": "Abundant marine life and minerals",
		"desc": "This is a lush, oceanic planet dominated by vast seas and rich marine ecosystems. The indigenous species, the Aquatic Serpentians, are well-adapted to underwater living and have built magnificent cities beneath the waves. Their industrial technology is centered around sustainable marine resource extraction.",
		"game_vars": {
			"scale_factor": 1,
			"anim_name": "Planet1",
			"spritesheet": "res://Assets/Sprites/Planets/twplanet3.png",
			"scan_cost": 20000
		}
	},
	# Planet index
	2: {
		"name": "Ignis Prime",
		"classification": "Terran Dry",
		"population": "50 thousand",
		"dom_species": "Human and Robot",
		"tech_level": "Machine Age",
		"resources": "Rare metals and minerals",
		"desc": "Resembling the Sol system's red planet with its arid surface and reddish hue, Ignis Prime houses several scientific colonies focused on extracting rare metals. Its harsh climate is managed by sophisticated robotic systems, making it primarily an outpost for exploration and resource gathering.",
		"game_vars": {
			"scale_factor": 1,
			"anim_name": "Planet2",
			"spritesheet": "res://Assets/Sprites/Planets/tdplanet1.png",
			"scan_cost": 30000
		}
	},
	# Planet index
	3: {
		"name": "Aurora Venti",
		"classification": "Gas Giant",
		"population": "3 billion",
		"dom_species": "Cloud Dwellers",
		"tech_level": "Atomic Age",
		"resources": "Helium-3 and floating flora",
		"desc": "This habitable gas giant supports a society of Cloud Dwellers residing on airborne city structures within its upper atmosphere. Thanks to advanced technologies, they harness energy from wind currents and atmospheric elements, living in harmony with the mesmerizing auroras that illuminate the gaseous skies.",
		"game_vars": {
			"scale_factor": 0.75,
			"anim_name": "Planet3",
			"spritesheet": "res://Assets/Sprites/Planets/gasplanet1.png",
			"scan_cost": 40000
		}
	}
}
